# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ppoirmeur/tetris/IN204-ProjetTetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ppoirmeur/tetris/IN204-ProjetTetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ppoirmeur/tetris/IN204-ProjetTetris/CMakeFiles /home/ppoirmeur/tetris/IN204-ProjetTetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ppoirmeur/tetris/IN204-ProjetTetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Time_Tetris

# Build rule for target.
Time_Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Time_Tetris
.PHONY : Time_Tetris

# fast build rule for target.
Time_Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/build
.PHONY : Time_Tetris/fast

Code/Affichage-Gtk/TetrisElements_Graphic-Piece.o: Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.o
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.o

# target to build an object file
Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.o
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.o

Code/Affichage-Gtk/TetrisElements_Graphic-Piece.i: Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.i
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.i

# target to preprocess a source file
Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.i
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.i

Code/Affichage-Gtk/TetrisElements_Graphic-Piece.s: Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.s
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.s

# target to generate assembly for a file
Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.s
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Piece.cpp.s

Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.o: Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.o
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.o

# target to build an object file
Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.o
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.o

Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.i: Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.i
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.i

# target to preprocess a source file
Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.i
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.i

Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.s: Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.s
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.s

# target to generate assembly for a file
Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.s
.PHONY : Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.cpp.s

Code/GameSystem/TetrisElements-Piece.o: Code/GameSystem/TetrisElements-Piece.cpp.o
.PHONY : Code/GameSystem/TetrisElements-Piece.o

# target to build an object file
Code/GameSystem/TetrisElements-Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Piece.cpp.o
.PHONY : Code/GameSystem/TetrisElements-Piece.cpp.o

Code/GameSystem/TetrisElements-Piece.i: Code/GameSystem/TetrisElements-Piece.cpp.i
.PHONY : Code/GameSystem/TetrisElements-Piece.i

# target to preprocess a source file
Code/GameSystem/TetrisElements-Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Piece.cpp.i
.PHONY : Code/GameSystem/TetrisElements-Piece.cpp.i

Code/GameSystem/TetrisElements-Piece.s: Code/GameSystem/TetrisElements-Piece.cpp.s
.PHONY : Code/GameSystem/TetrisElements-Piece.s

# target to generate assembly for a file
Code/GameSystem/TetrisElements-Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Piece.cpp.s
.PHONY : Code/GameSystem/TetrisElements-Piece.cpp.s

Code/GameSystem/TetrisElements-Terrain.o: Code/GameSystem/TetrisElements-Terrain.cpp.o
.PHONY : Code/GameSystem/TetrisElements-Terrain.o

# target to build an object file
Code/GameSystem/TetrisElements-Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Terrain.cpp.o
.PHONY : Code/GameSystem/TetrisElements-Terrain.cpp.o

Code/GameSystem/TetrisElements-Terrain.i: Code/GameSystem/TetrisElements-Terrain.cpp.i
.PHONY : Code/GameSystem/TetrisElements-Terrain.i

# target to preprocess a source file
Code/GameSystem/TetrisElements-Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Terrain.cpp.i
.PHONY : Code/GameSystem/TetrisElements-Terrain.cpp.i

Code/GameSystem/TetrisElements-Terrain.s: Code/GameSystem/TetrisElements-Terrain.cpp.s
.PHONY : Code/GameSystem/TetrisElements-Terrain.s

# target to generate assembly for a file
Code/GameSystem/TetrisElements-Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameSystem/TetrisElements-Terrain.cpp.s
.PHONY : Code/GameSystem/TetrisElements-Terrain.cpp.s

Code/GameWindow.o: Code/GameWindow.cpp.o
.PHONY : Code/GameWindow.o

# target to build an object file
Code/GameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameWindow.cpp.o
.PHONY : Code/GameWindow.cpp.o

Code/GameWindow.i: Code/GameWindow.cpp.i
.PHONY : Code/GameWindow.i

# target to preprocess a source file
Code/GameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameWindow.cpp.i
.PHONY : Code/GameWindow.cpp.i

Code/GameWindow.s: Code/GameWindow.cpp.s
.PHONY : Code/GameWindow.s

# target to generate assembly for a file
Code/GameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/GameWindow.cpp.s
.PHONY : Code/GameWindow.cpp.s

Code/Random.o: Code/Random.cpp.o
.PHONY : Code/Random.o

# target to build an object file
Code/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Random.cpp.o
.PHONY : Code/Random.cpp.o

Code/Random.i: Code/Random.cpp.i
.PHONY : Code/Random.i

# target to preprocess a source file
Code/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Random.cpp.i
.PHONY : Code/Random.cpp.i

Code/Random.s: Code/Random.cpp.s
.PHONY : Code/Random.s

# target to generate assembly for a file
Code/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/Random.cpp.s
.PHONY : Code/Random.cpp.s

Code/TimeManager.o: Code/TimeManager.cpp.o
.PHONY : Code/TimeManager.o

# target to build an object file
Code/TimeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/TimeManager.cpp.o
.PHONY : Code/TimeManager.cpp.o

Code/TimeManager.i: Code/TimeManager.cpp.i
.PHONY : Code/TimeManager.i

# target to preprocess a source file
Code/TimeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/TimeManager.cpp.i
.PHONY : Code/TimeManager.cpp.i

Code/TimeManager.s: Code/TimeManager.cpp.s
.PHONY : Code/TimeManager.s

# target to generate assembly for a file
Code/TimeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/TimeManager.cpp.s
.PHONY : Code/TimeManager.cpp.s

Code/main.o: Code/main.cpp.o
.PHONY : Code/main.o

# target to build an object file
Code/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/main.cpp.o
.PHONY : Code/main.cpp.o

Code/main.i: Code/main.cpp.i
.PHONY : Code/main.i

# target to preprocess a source file
Code/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/main.cpp.i
.PHONY : Code/main.cpp.i

Code/main.s: Code/main.cpp.s
.PHONY : Code/main.s

# target to generate assembly for a file
Code/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time_Tetris.dir/build.make CMakeFiles/Time_Tetris.dir/Code/main.cpp.s
.PHONY : Code/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Time_Tetris"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Piece.o"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Piece.i"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Piece.s"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.o"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.i"
	@echo "... Code/Affichage-Gtk/TetrisElements_Graphic-Terrain.s"
	@echo "... Code/GameSystem/TetrisElements-Piece.o"
	@echo "... Code/GameSystem/TetrisElements-Piece.i"
	@echo "... Code/GameSystem/TetrisElements-Piece.s"
	@echo "... Code/GameSystem/TetrisElements-Terrain.o"
	@echo "... Code/GameSystem/TetrisElements-Terrain.i"
	@echo "... Code/GameSystem/TetrisElements-Terrain.s"
	@echo "... Code/GameWindow.o"
	@echo "... Code/GameWindow.i"
	@echo "... Code/GameWindow.s"
	@echo "... Code/Random.o"
	@echo "... Code/Random.i"
	@echo "... Code/Random.s"
	@echo "... Code/TimeManager.o"
	@echo "... Code/TimeManager.i"
	@echo "... Code/TimeManager.s"
	@echo "... Code/main.o"
	@echo "... Code/main.i"
	@echo "... Code/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

