# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ppoirmeur/tetris/IN204-ProjetTetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ppoirmeur/tetris/IN204-ProjetTetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ppoirmeur/tetris/IN204-ProjetTetris/CMakeFiles /home/ppoirmeur/tetris/IN204-ProjetTetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ppoirmeur/tetris/IN204-ProjetTetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

GameWindow.o: GameWindow.cpp.o
.PHONY : GameWindow.o

# target to build an object file
GameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GameWindow.cpp.o
.PHONY : GameWindow.cpp.o

GameWindow.i: GameWindow.cpp.i
.PHONY : GameWindow.i

# target to preprocess a source file
GameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GameWindow.cpp.i
.PHONY : GameWindow.cpp.i

GameWindow.s: GameWindow.cpp.s
.PHONY : GameWindow.s

# target to generate assembly for a file
GameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GameWindow.cpp.s
.PHONY : GameWindow.cpp.s

Random.o: Random.cpp.o
.PHONY : Random.o

# target to build an object file
Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.o
.PHONY : Random.cpp.o

Random.i: Random.cpp.i
.PHONY : Random.i

# target to preprocess a source file
Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.i
.PHONY : Random.cpp.i

Random.s: Random.cpp.s
.PHONY : Random.s

# target to generate assembly for a file
Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.s
.PHONY : Random.cpp.s

TetrisElements-Piece.o: TetrisElements-Piece.cpp.o
.PHONY : TetrisElements-Piece.o

# target to build an object file
TetrisElements-Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Piece.cpp.o
.PHONY : TetrisElements-Piece.cpp.o

TetrisElements-Piece.i: TetrisElements-Piece.cpp.i
.PHONY : TetrisElements-Piece.i

# target to preprocess a source file
TetrisElements-Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Piece.cpp.i
.PHONY : TetrisElements-Piece.cpp.i

TetrisElements-Piece.s: TetrisElements-Piece.cpp.s
.PHONY : TetrisElements-Piece.s

# target to generate assembly for a file
TetrisElements-Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Piece.cpp.s
.PHONY : TetrisElements-Piece.cpp.s

TetrisElements-Terrain.o: TetrisElements-Terrain.cpp.o
.PHONY : TetrisElements-Terrain.o

# target to build an object file
TetrisElements-Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Terrain.cpp.o
.PHONY : TetrisElements-Terrain.cpp.o

TetrisElements-Terrain.i: TetrisElements-Terrain.cpp.i
.PHONY : TetrisElements-Terrain.i

# target to preprocess a source file
TetrisElements-Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Terrain.cpp.i
.PHONY : TetrisElements-Terrain.cpp.i

TetrisElements-Terrain.s: TetrisElements-Terrain.cpp.s
.PHONY : TetrisElements-Terrain.s

# target to generate assembly for a file
TetrisElements-Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements-Terrain.cpp.s
.PHONY : TetrisElements-Terrain.cpp.s

TetrisElements_Graphic-Piece.o: TetrisElements_Graphic-Piece.cpp.o
.PHONY : TetrisElements_Graphic-Piece.o

# target to build an object file
TetrisElements_Graphic-Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Piece.cpp.o
.PHONY : TetrisElements_Graphic-Piece.cpp.o

TetrisElements_Graphic-Piece.i: TetrisElements_Graphic-Piece.cpp.i
.PHONY : TetrisElements_Graphic-Piece.i

# target to preprocess a source file
TetrisElements_Graphic-Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Piece.cpp.i
.PHONY : TetrisElements_Graphic-Piece.cpp.i

TetrisElements_Graphic-Piece.s: TetrisElements_Graphic-Piece.cpp.s
.PHONY : TetrisElements_Graphic-Piece.s

# target to generate assembly for a file
TetrisElements_Graphic-Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Piece.cpp.s
.PHONY : TetrisElements_Graphic-Piece.cpp.s

TetrisElements_Graphic-Terrain.o: TetrisElements_Graphic-Terrain.cpp.o
.PHONY : TetrisElements_Graphic-Terrain.o

# target to build an object file
TetrisElements_Graphic-Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Terrain.cpp.o
.PHONY : TetrisElements_Graphic-Terrain.cpp.o

TetrisElements_Graphic-Terrain.i: TetrisElements_Graphic-Terrain.cpp.i
.PHONY : TetrisElements_Graphic-Terrain.i

# target to preprocess a source file
TetrisElements_Graphic-Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Terrain.cpp.i
.PHONY : TetrisElements_Graphic-Terrain.cpp.i

TetrisElements_Graphic-Terrain.s: TetrisElements_Graphic-Terrain.cpp.s
.PHONY : TetrisElements_Graphic-Terrain.s

# target to generate assembly for a file
TetrisElements_Graphic-Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic-Terrain.cpp.s
.PHONY : TetrisElements_Graphic-Terrain.cpp.s

TimeManager.o: TimeManager.cpp.o
.PHONY : TimeManager.o

# target to build an object file
TimeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TimeManager.cpp.o
.PHONY : TimeManager.cpp.o

TimeManager.i: TimeManager.cpp.i
.PHONY : TimeManager.i

# target to preprocess a source file
TimeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TimeManager.cpp.i
.PHONY : TimeManager.cpp.i

TimeManager.s: TimeManager.cpp.s
.PHONY : TimeManager.s

# target to generate assembly for a file
TimeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TimeManager.cpp.s
.PHONY : TimeManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... GameWindow.o"
	@echo "... GameWindow.i"
	@echo "... GameWindow.s"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... TetrisElements-Piece.o"
	@echo "... TetrisElements-Piece.i"
	@echo "... TetrisElements-Piece.s"
	@echo "... TetrisElements-Terrain.o"
	@echo "... TetrisElements-Terrain.i"
	@echo "... TetrisElements-Terrain.s"
	@echo "... TetrisElements_Graphic-Piece.o"
	@echo "... TetrisElements_Graphic-Piece.i"
	@echo "... TetrisElements_Graphic-Piece.s"
	@echo "... TetrisElements_Graphic-Terrain.o"
	@echo "... TetrisElements_Graphic-Terrain.i"
	@echo "... TetrisElements_Graphic-Terrain.s"
	@echo "... TimeManager.o"
	@echo "... TimeManager.i"
	@echo "... TimeManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

