# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/will/Desktop/Cours/IN204/ProjetTetris/IN204-ProjetTetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/will/Desktop/Cours/IN204/ProjetTetris/IN204-ProjetTetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Desktop/Cours/IN204/ProjetTetris/IN204-ProjetTetris/CMakeFiles /home/will/Desktop/Cours/IN204/ProjetTetris/IN204-ProjetTetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Desktop/Cours/IN204/ProjetTetris/IN204-ProjetTetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

GTK-Setup.o: GTK-Setup.cpp.o
.PHONY : GTK-Setup.o

# target to build an object file
GTK-Setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GTK-Setup.cpp.o
.PHONY : GTK-Setup.cpp.o

GTK-Setup.i: GTK-Setup.cpp.i
.PHONY : GTK-Setup.i

# target to preprocess a source file
GTK-Setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GTK-Setup.cpp.i
.PHONY : GTK-Setup.cpp.i

GTK-Setup.s: GTK-Setup.cpp.s
.PHONY : GTK-Setup.s

# target to generate assembly for a file
GTK-Setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GTK-Setup.cpp.s
.PHONY : GTK-Setup.cpp.s

Random.o: Random.cpp.o
.PHONY : Random.o

# target to build an object file
Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.o
.PHONY : Random.cpp.o

Random.i: Random.cpp.i
.PHONY : Random.i

# target to preprocess a source file
Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.i
.PHONY : Random.cpp.i

Random.s: Random.cpp.s
.PHONY : Random.s

# target to generate assembly for a file
Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Random.cpp.s
.PHONY : Random.cpp.s

TetrisElements.o: TetrisElements.cpp.o
.PHONY : TetrisElements.o

# target to build an object file
TetrisElements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements.cpp.o
.PHONY : TetrisElements.cpp.o

TetrisElements.i: TetrisElements.cpp.i
.PHONY : TetrisElements.i

# target to preprocess a source file
TetrisElements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements.cpp.i
.PHONY : TetrisElements.cpp.i

TetrisElements.s: TetrisElements.cpp.s
.PHONY : TetrisElements.s

# target to generate assembly for a file
TetrisElements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements.cpp.s
.PHONY : TetrisElements.cpp.s

TetrisElements_Graphic.o: TetrisElements_Graphic.cpp.o
.PHONY : TetrisElements_Graphic.o

# target to build an object file
TetrisElements_Graphic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic.cpp.o
.PHONY : TetrisElements_Graphic.cpp.o

TetrisElements_Graphic.i: TetrisElements_Graphic.cpp.i
.PHONY : TetrisElements_Graphic.i

# target to preprocess a source file
TetrisElements_Graphic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic.cpp.i
.PHONY : TetrisElements_Graphic.cpp.i

TetrisElements_Graphic.s: TetrisElements_Graphic.cpp.s
.PHONY : TetrisElements_Graphic.s

# target to generate assembly for a file
TetrisElements_Graphic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/TetrisElements_Graphic.cpp.s
.PHONY : TetrisElements_Graphic.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... GTK-Setup.o"
	@echo "... GTK-Setup.i"
	@echo "... GTK-Setup.s"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... TetrisElements.o"
	@echo "... TetrisElements.i"
	@echo "... TetrisElements.s"
	@echo "... TetrisElements_Graphic.o"
	@echo "... TetrisElements_Graphic.i"
	@echo "... TetrisElements_Graphic.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

